### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by MyFilippo94** [Egocentrix/AC-UDP-Connection#1]
Hello, I would like to know what license is this code release under, I can not find any informations in the code itself. Thanks for sharing your work!

**Comment by coffeelake** [comment]
Hi,
For now it´s licence is "GNU General Public License, version 3 (GPLv3)"
I haven't thought about this and it may be changed in a near future

**Comment by MyFilippo94** [comment]
Alright, GNU GPL V3.
Thanks for answering!
